#!/bin/bash

for ((i=1;i<=$1;i++))
do 
    echo $i
    qsub -V -N run_t_$i -w e -l qname=itf.q -pe openmpi 6 -o 'job_output/$JOB_NAME-$JOB_ID.log' -j y -cwd run_graphene_continuum_limit_script $i "$2" "$3_$i.csv"    
done