#!/bin/bash
~/bin/julia ~/GrapheneHMC/tests/TestToolsjl
~/bin/julia ~/GrapheneHMC/tests/TestHexagonalLattice.jl
~/bin/julia ~/GrapheneHMC/tests/TestFermionicMatrix.jl
~/bin/julia ~/GrapheneHMC/tests/TestAction.jl
~/bin/julia ~/GrapheneHMC/tests/TestPotential.jl
~/bin/julia ~/GrapheneHMC/tests/Test_ComplexRand.jl
~/bin/julia ~/GrapheneHMC/tests/TestIntegrators.jl
~/bin/julia ~/GrapheneHMC/tests/TestHMC.jl





